.Dd 26 April 2001
.Os
.Dt SEX 6
.Sh NAME
.Nm Sex
.Nd spout silly, random porn-like text
.Sh SYNOPSIS
.Nm sex
.Op Fl w Op Ar width
.Sh DESCRIPTION
.Nm sex
spouts a silly mad-lib-like random porn-style text.  Wraps text, 
optionally at
.Ar width
, if
.Fl w
is used.
.Sh AUTHOR
.An Unknown.  Adopted and cleaned up by Nick Johnson <freebsd@spatula.net>.
